<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/28
 * Time: 10:52
 */

namespace App\Http\Controllers\Login;

use App\Http\Controllers\FBaseController;
use App\Model\Blog_user;
use Symfony\Component\HttpFoundation\Request;

class LoginController extends FBaseController
{
    public function __call($method, $parameters)
    {
        parent::__call($method, $parameters); // TODO: Change the autogenerated stub

    }

    /*
     * login 页面
     */
    public function loginView(){
        return view("/login/loginview");
    }

    //loginstart
    /*
     * reg
     */
    public function regUser(Request $request) {
        $user_model = new Blog_user();
        $data = array(
            "username"=>$request->input("username"),
            "password"=>$request->input("password"),
            "nickname"=>$request->input("nickname")
        );
        //验证用户名唯一
        $userinfo = $user_model->getOneUserInfo(['username'=>$data['username']]);
        if($userinfo){
            showMsg(1002,"用户名已经存在,请更换用户名",[]);
        }
        $res = $user_model->regNewUser($data);
        if($res){
            showMsg(1000,"注册成功",$res);

        }else{
            showMsg(1001,"注册失败",[]);
        }
    }
    /*
     * login
     */
    public function login(Request $request)
    {

    }
    //loginend
}